version: "3.5"
services:
  backend-service:
    container_name: backend-dev
    image: telidoc/backend:dev
    ports:
      - "8001:3000"
    networks:
      - back

networks:
  back:
    name: backend
    external: true
